Don't go past lwjgl 3.3.3
3.3.4 introduced changes that break the minecraft compile.
This is the compile error:
> Task :compileJava
/Users/joe/src/tt-minerl/minerl/MCP-Reborn/src/main/java/net/minecraft/client/renderer/texture/NativeImage.java:433: error: cannot find symbol
         STBImageResize.nstbir_resize_uint8(this.imagePointer + (long)((xIn + yIn * this.getWidth()) * i), widthIn, heightIn, this.getWidth() * i, imageIn.imagePointer, imageIn.getWidth(), imageIn.getHeight(), 0, i);
                       ^
  symbol:   method nstbir_resize_uint8(long,int,int,int,long,int,int,int,int)
  location: class STBImageResize

Probably this from the 3.3.4 change logs:
https://github.com/LWJGL/lwjgl3/releases/tag/3.3.4
stb
Updated stb_image to 2.30 (up from 2.28)
Updated stb_image_resize to 2.09 (up from 0.97)